# Generated by Django 6.0.1 on 2026-04-13 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='farmerprofile',
            name='is_verified',
            field=models.BooleanField(default=False, help_text='Верифицирован администратором'),
        ),
    ]
