# Generated by Django 6.0.1 on 2026-04-15 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_is_verified_alter_user_activation_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='activation_code',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
    ]
